<?php include('connection.php')?>

<!-- for error hide -->
<?php
error_reporting(0);
?>
<!-- for error hide -->

<?php
// $entered_event_name = Null;
// if (isset($_POST['event_name'])) {
$entered_event_name = $_POST['event_name'];
$sql = 'SELECT * FROM audience WHERE reg_event ="'.$entered_event_name.'"';
$retval = mysqli_query($con,$sql);
// }
?>

<?php include('includes/head.php')?>

<div class="concontainer-fluid container text-center " id="">
      <form method="POST">
        <h1>Select Event List</h1>
        <select name="event_name" class="form-control">
          <option>Select Event List</option>
          <?php
                $sql = 'SELECT * FROM events';
                $res = mysqli_query($con,$sql);
                ?>
            <?php  while($row = mysqli_fetch_assoc($res))
                {
                  ?>
                <option name="add_event_name">
                  <?php   echo $row['event_name']?>
                  <?php
                    }
                    ?>
                </option>
              </select>
              <br>
              <input type="submit" class="btn btn-warning w-25">
      </form>

    </div>
<div class="container bg-white rounded p-4" >
  <div class="row justify-content-center mb-4">
    <div class="col-md-9 ">
      <img src="images/q.png" class="rounded mx-auto py-3 d-block" width=35% alt="srmslogo">
    </div>
    <div class="text-theme text-center">
      <h5>SHRI RAM MURTI SMARAK COLLEGE OF ENGINEERNING & TECHNOLOGY,BAREILLY</h5>
      <h5>Ram Murti Puram, Bareilly - Nainital Rd, Highway, Bhojipura, Uttar Pradesh 243202</h5>
      <h2><b>Parivartan "Ek Chakra"</b></h2>
      <h4 class="pt-1">Zest 2022 Registration Details</h4><br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Event Name</th>
            <td class="align-left py-2" width=30><?php echo $entered_event_name ?></td>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30>Admin </td> 
          </tr>
          <tr>
         
          <th class="align-middle py-2" width=20% scope="row">EID</th>
            <td class="align-left py-2"> <?php  ?> </td>
            <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo "". date("Y-m-d") .""; ?></td>
            <?php
   
            ?>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Student List</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
          <th scope="col" style="width:21%">EID</th>
              <th scope="col" style="width:21%">PID</th>
              <th scope="col" style="width:35%">Event Name</th>
              <th scope="col" style="width:37%">Action</th>
            </tr>
            <!-- <th scope="col" style="width:25%">Action </th> -->
          </tr>
        </thead>
        <tbody>
        <?php
   while ($row = mysqli_fetch_assoc($retval)) {
    if ($row['eid']>0) {
      # code...
    ?>
          <tr>
            <td>
              <?php
         echo $row["eid"];
         $eid = $row["eid"];
         ?>
            </td>
            <td>
              <?php
         echo $row["pid"]
         ?>
            </td>
            <td>
              <?php
         echo $row["reg_event"]
         ?>
            </td>
            <td>
              <?php
         echo $row["venue"]
         ?>
            </td>
          </tr>
          <?php
    }
      
   }
   ?>
        </tbody>
      </table>
    </div>
    <!-- {% endif %} -->
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <!-- <a href="register_event.php" class="btn btn-color serach-btn mx-2">Register for Event</a> -->
      </form>
    </div>
  </div>
  </div>
</div>
<div class="d-flex" id="wrapper">
  <!-- Page content wrapper-->
  <div id="page-content-wrapper">
    <?php include('includes/navbar.php')?>
    <!-- Page content-->
    
  </div>
</div>

   
<?php include('includes/footer.php')?>