<?php include('includes/head.php')?>
<?php include('connection.php')?>
<?php
session_start();



?>
<body>
<?php include('includes/navbar.php')?>
<div class="container bg-white rounded p-4" >
  <div class="row justify-content-center mb-4">
    <div class="col-md-9 ">
      <img src="images/q.png" class="rounded mx-auto py-3 d-block" width=35% alt="srmslogo">
    </div>
    <div class="text-theme text-center">
      <h5>SHRI RAM MURTI SMARAK COLLEGE OF ENGINEERNING & TECHNOLOGY,BAREILLY</h5>
      <h5>Ram Murti Puram, Bareilly - Nainital Rd, Highway, Bhojipura, Uttar Pradesh 243202</h5>
      <h2><b>Parivartan "Ek Chakra"</b></h2>
      <h4 class="pt-1">Zest 2022 Registration Details</h4><br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">PID</th>
            <td class="align-left py-2" width=30%><?php echo $_SESSION['pid'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Name</th>
            <td class="align-left py-2"><?php echo $_SESSION['name'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">College Name</th>
            <td class="align-left py-2" width=30%><?php echo $_SESSION['college'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Roll Number</th>
            <td class="align-left py-2"><?php echo $_SESSION['roll_no'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Batch</th>
            <td class="align-left py-2" width=30%><?php echo $_SESSION['batch'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Course</th>
            <td class="align-left py-2"><?php echo $_SESSION['courses'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Branch</th>
            <td class="align-left py-2" width=30%><?php echo $_SESSION['branch'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Gender</th>
            <td class="align-left py-2"><?php echo $_SESSION['gender'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30><?php echo $level1['level']; ?></td>
            <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo "". date("Y-m-d") .""; ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Phone</th>
            <td class="align-left py-2" width=30%><?php echo $_SESSION['phone'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Email</th>
            <td class="align-left py-2"><?php echo $_SESSION['email'] ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Event</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
            <th scope="col" style="width:45%">Event Name </th>
            <th scope="col" style="width:30%">Event Venue </th>
            <th scope="col" style="width:25%">Event Date and Time </th>
            <!-- <th scope="col" style="width:25%">Action </th> -->
          </tr>
        </thead>
        <tbody>
        <!-- {% for event in pid.pid_event.all%} -->
          
          <?php
            $res1 = mysqli_query($con,"SELECT * FROM audience WHERE pid= '" .$_SESSION['pid']. "' ");
            while ($ress1 = mysqli_fetch_assoc($res1)) {
            ?>
            <tr>
              <td><?php echo $ress1['reg_event']?></td>
              <td><?php echo $ress1['venue']?></td>
              <td><?php echo $ress1['event_start_time']?></td>
              



            </tr>
            <?php
            }
            ?>
        <!-- {% endfor %} -->
        </tbody>
      </table>
    </div>
    <!-- {% endif %} -->
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <a href="register_event.php" class="btn btn-color serach-btn mx-2">Register for Event</a>
      </form>
    </div>
  </div>
  </div>
</div>
<?php include('includes/footer.php')?>