<?php include('includes/head.php')?>
<?php include('connection.php')?>
<?php
session_start();
$_SESSION['f_tid'] = $_GET['TID'];
$qry1 ="SELECT * from tid WHERE TID ='".$_GET['TID']."'";

$res11 = mysqli_query($con,$qry1);
$row = mysqli_fetch_assoc($res11);

?>
<body>
<?php include('includes/navbar.php')?>
<div class="container bg-white rounded p-5">
  <div class="row justify-content-center mb-4">
    <div class="col-md-9 ">
      <img src="images/q.png" class="rounded mx-auto py-3 d-block" width=35% alt="srmslogo">
    </div>
    <div class="text-theme text-center">
      <h5>SHRI RAM MURTI SMARAK COLLEGE OF ENGINEERNING & TECHNOLOGY,BAREILLY</h5>
      <h5>Ram Murti Puram, Bareilly - Nainital Rd, Highway, Bhojipura, Uttar Pradesh 243202</h5>
      <h2><b>Parivartan "Ek Chakra"</b></h2>
      <h4 class="pt-0">Zest 2022 Registration Details</h4>
      <h4 class="pt-1">TID Slip</h4><br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=30% scope="row">PID</th>
            <td class="align-left py-2" width=60%><?php echo $row['TID'] ?></td>

          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">College Name</th>
            <td class="align-left py-2" width=30%><?php echo $row['college'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30><?php echo $row['generated_by'] ?></td>
          </tr>
          <tr>
          <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo $row['date'] ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Event</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
          <th scope="col" style="width:15%">PID in <?php echo $_GET['TID'];?> </th>  
          <th scope="col" style="width:35%">Event Name </th>
            <th scope="col" style="width:30%">Event Venue </th>
            <th scope="col" style="width:35%">Event Date and Time </th>
          </tr>
        </thead>
        <tbody>
        <?php
            $res1 = mysqli_query($con,"SELECT * FROM audience WHERE tid= '".$_GET['TID']."' ");
            while ($ress1 = mysqli_fetch_assoc($res1)) 
            {
              if($ress1['eid']>0){
            ?>
        <tr>
          <td><?php echo $ress1['pid']?></td>
          <td><?php echo $ress1['reg_event']?></td>
          <td><?php echo $ress1['venue']?></td>
          <td><?php echo $ress1['event_start_time']?></td>
          <td>
            <?php
              }
            }
            ?>
        </tbody>
      </table>
    </div>
    <!-- {% endif %} -->
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <a href="find_pid_registration_team.php" class="btn btn-color serach-btn mx-2">Register for Event</a>
      </form>
    </div>
  </div>
  </div>
</div>
<?php include('includes/footer.php')?>