<?php include('includes/header.php')?>
<?php include('connection.php')?>
<?php
session_start();
$qry1 ="SELECT * from pid WHERE pid ='".$_GET['pid']."'";
$res11 = mysqli_query($con,$qry1);
$row = mysqli_fetch_assoc($res11);

?>

<body>
<?php include('includes/navbar.php')?>
<div class="d-flex" id="wrapper">
           <?php include('includes/sidebar.php')?>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
            <div class="container bg-white rounded p-5" >
  <div class="row justify-content-center mb-4">
    <div class="col-md-9 ">
      <img src="assets/q.png" class="rounded mx-auto py-3 d-block" width=35% alt="srmslogo">
    </div>
    <div class="text-theme text-center">
      <h5>SHRI RAM MURTI SMARAK COLLEGE OF ENGINEERNING & TECHNOLOGY,BAREILLY</h5>
      <h5>Ram Murti Puram, Bareilly - Nainital Rd, Highway, Bhojipura, Uttar Pradesh 243202</h5>
      <h2><b>Parivartan "Ek Chakra"</b></h2>
      <h4 class="pt-0">Zest 2022 Registration Details</h4>
      <h4 class="pt-1">PID Slip</h4><br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-bordered bg-white ">
        <tbody>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">PID</th>
            <td class="align-left py-2" width=30%><?php echo $row['pid'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Name</th>
            <td class="align-left py-2"><?php echo $row['name'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">College Name</th>
            <td class="align-left py-2" width=30%><?php echo $row['college'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Roll Number</th>
            <td class="align-left py-2"><?php echo $row['roll_no'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Batch</th>
            <td class="align-left py-2" width=30%><?php echo $row['batch'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Course</th>
            <td class="align-left py-2"><?php echo $row['course'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Branch</th>
            <td class="align-left py-2" width=30%><?php echo $row['branch'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Gender</th>
            <td class="align-left py-2"><?php echo $row['gender'] ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Generated by</th>
            <td class="align-left py-2" width=30></td>
            <th class="align-middle py-2" width=20% scope="row">Registration Date</th>
            <td class="align-left py-2">  <?php echo "". date("Y-m-d") .""; ?></td>
          </tr>
          <tr>
            <th class="align-middle py-2" width=20% scope="row">Phone</th>
            <td class="align-left py-2" width=30%><?php echo $row['phone'] ?></td>
            <th class="align-middle py-2" width=20% scope="row">Email</th>
            <td class="align-left py-2"><?php echo $row['email'] ?></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr class="text-center">
            <th scope="col" style="width:50%">Registered Event</th>
          </tr>
        </thead>
      </table>  
    </div>
    <div class="col-md-12">  
      <table class="table table-bordered table-hover bg-white">
        <thead>
          <tr>
            <th scope="col" style="width:45%">Event Name </th>
            <th scope="col" style="width:30%">Event Venue </th>
            <th scope="col" style="width:25%">Event Date and Time </th>
            <!-- <th scope="col" class="" style="width:15%">Action</th> -->
          </tr>
        </thead>
        <tbody>
        <!-- {% for event in pid.pid_event.all%} -->
          
            <?php
            $res1 = mysqli_query($con,"SELECT * FROM audience WHERE pid= '" .$_GET['pid']. "' ");
            while ($ress1 = mysqli_fetch_assoc($res1)) {
            ?>
            <tr>
              <td><?php echo $ress1['reg_event']?></td>
              <td><?php echo $ress1['venue']?></td>
              <td><?php echo $ress1['event_start_time']?></td>
              
            </tr>
            <!-- <td class="align-middle py-2" width=45%><?php $ress1['reg_event']?></td>
            <td class="align-middle py-2" width=30%><?php $ress1['venue']?></td>
            <td class="align-middle py-2" width=25%><?php $ress1['reg_event']?></td> -->
            <?php
            }
            ?>
          
        <!-- {% endfor %} -->
        </tbody>
      </table>
    </div>
    <!-- {% endif %} -->
  </div>
  <div class="container">
  <div class="row d-print-none">
    <div class="col-md-12 mt-2  text-center">
      <form>
        <input class="btn btn-color serach-btn " type="button" value="Print this page" onClick="window.print()">
        <a href="register_event.php" class="btn btn-color serach-btn mx-2">Register for Event</a>
      </form>
    </div>
  </div>
  </div>
</div>
            </div>
</div>

<?php include('includes/footer.php')?>